openapi: 3.0.3
info:
  title: 고객센터
  description: |-
    Tmax Commerce 제품 MyShopStudio(고객용)
      - '고객센터'  서비스컴포넌트
      - 해당 MyShop을 이용하는 고객들을 대상으로 FAQ, 문의게시판을 제공하는 기능
        - FAQ : 리스트 형태로 제공 
        - 문의게시판 : 리스트 형태로 제공
  version: 1.0.11
servers:
  - url: sample
tags:
  - name: faq
    description: FAQ
  - name: enquiry
    description: 문의게시판
  - name: faq / enquiry (와플 게시판)
    description: |-
      - guide / faq / announcementsms 전형적인 게시판형 기능에 속함
      - 게시판 관련 컴포넌트는 와플 게시판을 통해 구현한다는 내용이 있었음 
      - 해당 내용에 대한 진척사항, 히스토리 파악 필요
paths:
  /faq:
    get:
      tags:
        - faq
      summary: FAQ 목록 조회
      description: 고객센터>FAQ   FAQ 목록을 조회한다.
      operationId: findFAQ
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
        - name: keyword
          in: query
          description: keyword
          schema:
            type: string
        - name: faqType
          in: query
          description: faqType
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FAQ"

  /enquiry:
    get:
      tags:
        - enquiry
      summary: 문의목록 조회
      description: 고객관리 > 문의관리 문의목록을 조회한다.
      operationId: findEnquiry
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
        - name: userId
          in: header
          description: userId ( waplId )
          schema:
            type: string
        - name: keyword
          in: query
          description: keyword
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Enquiry"

    post:
      tags:
        - enquiry
      summary: 문의 등록
      description: 문의를 등록한다
      operationId: registerEnquiry
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
        - name: userId
          in: header
          description: userId ( waplId )
          schema:
            type: string
      requestBody:
        description: 새 문의를 등록한다
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnquiryRegisterInfo"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Enquiry"

  /enquiry/{enquiryId}:
    delete:
      tags:
        - enquiry
      summary: 문의 삭제
      description: 문의를 삭제한다
      operationId: deleteEnquiryReply
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
        - name: userId
          in: header
          description: userId ( waplId )
          schema:
            type: string
        - name: enquiryId
          in: path
          description: enquiryId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Enquiry"
components:
  schemas:
    FAQ:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: FAQ Id
          example: 10
        type:
          $ref: "#/components/schemas/FAQType"
        title:
          type: string
          description: FAQ 제목
          example: 현금영수증을 신청하고 싶어요
        content:
          type: string
          description: FAQ 내용
          example: this is sample content
        activated:
          type: boolean
          description: 활성화상태
          example: true
        date:
          type: string
          description: 작성일자
          example: 2023-03-07
      xml:
        name: faq

    FAQType:
      type: object
      description: FAQ 유형
      properties:
        id:
          type: string
          description: FAQ 유형ID
          example: 10
        title:
          type: string
          description: FAQ 유형 제목
          example: 상품문의
        order:
          type: number
          description: FAQ 유형 순서
          example: 상품문의
      xml:
        name: faqType

    Enquiry:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: 문의 Id
          example: 10
        number:
          type: string
          format: int64
          description: 문의번호
          example: 10
        question:
          type: string
          description: 문의내용
          example: 바스크 치즈 케이크 품절 언제 풀리나요?
        answer:
          type: string
          description: 답변내용
          example: 내일 풀립니다
        images:
          description: 이미지
          type: array
          items:
            type: object
            properties:
              fileId:
                type: string
                description: 이미지파일ID
                example: 10
              fileUri:
                type: string
                description: 이미지URI
                example: 1231231asd
        orderId:
          type: string
          description: 주문번호
          example: 하도야지
        nickname:
          type: string
          description: 작성자
          example: 하도야지
        replyed:
          type: boolean
          description: 답변여부
          example: true
      xml:
        name: enquiry

    EnquiryRegisterInfo:
      type: object
      properties:
        question:
          type: string
          description: 문의내용
          example: 바스크 치즈 케이크 품절 언제 풀리나요?
        images:
          description: 이미지
          type: array
          items:
            type: object
            properties:
              fileId:
                type: string
                description: 이미지파일ID
                example: 10
              fileUri:
                type: string
                description: 이미지URI
                example: 1231231asd
        orderId:
          type: string
          description: 주문번호
          example: 하도야지
      xml:
        name: enquiryRegisterInfo
