openapi: 3.0.3
info:
  title: 전체상품관리
  description: |-
    Tmax Commerce 제품 MyShopStudio(점주용)
      - '전체상품관리' 메뉴(도메인) 서비스컴포넌트

    Tmax Commerce 제품 MyShop(고객용) : 전체상품관리에서 전체 커버 가능할 것으로 생각됨 (전체상품 관리에서 조회 부분만 차용)
      - '상품목록' 서비스컴포넌트  
      - '상품상세' 서비스컴포넌트
  version: 1.0.11
servers:
  - url: sample
tags:
  - name: category
    description: 상품 내 카테고리
  - name: product
    description: 상품 정보
  - name: origins
    description: 원산지 정보
paths:
  /product/category:
    get:
      tags:
        - category
      summary: 카테고리목록 및 상품 조회
      description: 상품목록 화면 진입 시 카테고리 별 상품목록을 조회한다.
      operationId: findCategoriesWithProducts
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryWithProducts"

  /product/{categoryId}/{productId}:
    get:
      tags:
        - product
      summary: 상품목록 단건 조회
      description: |-
        - 상품목록에서 상품 클릭 시 해당 상품에 대한 상세정보를 조회한다.
      operationId: findProductsByCategoryIdAndProductId
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
        - name: categoryId
          in: path
          description: categoryId
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: product
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  /origins:
    get:
      tags:
        - origins
      summary: 원산지표기정보 조회
      description: 원산지표기정보를 조회한다.
      operationId: findOrigins
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Origins"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: 상품Id
          example: 10
        name:
          type: string
          description: 상품명
          example: chicken
        description:
          type: string
          description: 상품 설명
          example: this is sample description
        price:
          type: number
          description: 가격
          example: 10000
        order:
          type: number
          description: 상품 순서
          example: 0
        image:
          type: array
          items:
            type: string
          description: 상품 이미지
          example: url
        salesStatus:
          type: string
          description: 상품 판매 상태
          example: test
        isNew:
          type: boolean
          description: 신상품 여부
          example: Y
        isRecommand:
          type: boolean
          description: 상품추천 여부
          example: Y
        orderType:
          type: string
          description: 상품 주문 타입
          example: shipping
      xml:
        name: product

    CategoryWithProducts:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: 카테고리Id
          example: 10
        name:
          type: string
          example: doggie
          description: 카테고리명
        description:
          type: string
          description: 카테고리 설명
          example: this is sample description
        order:
          type: number
          description: 카테고리 순서
          example: 0
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
          description: 상품

    Option:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: 옵션Id
          example: 10
        name:
          type: string
          description: 옵션명
          example: 핫소스
        price:
          type: number
          description: 옵션가격
          example: true
        salesStatus:
          type: string
          description: 옵션 판매 상태
          example: test
        order:
          type: number
          description: 옵션 순서
          example: 1
      xml:
        name: option

    Origins:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: originsId
          example: 10
        description:
          type: string
          description: 원산지표기정보
          example: testetstsets
      xml:
        name: origins
