openapi: 3.0.3
info:
  title: 고객지원
  description: |-
    Tmax Commerce 제품 MyShopStudio(점주용)
      - '고객지원'  서비스컴포넌트
      - MyShopStudio를 이용하는 점주들을 대상으로 MyShopStudio 사용 가이드, FAQ, 공지사항을 제공하는 기능
        - 가이드 : PDF 다운로드 형태로 제공
        - FAQ : 게시판 형태로 제공 
        - 공지사항 (GNB 탭의 공지사항(announcement)과 동일)
      - 이전 버전 기획 기반으로 구성
      - ** PM 쪽에서 해당 정보 입력 위한 Master 서비스 필요함 **
  version: 1.0.11
servers:
  - url: sample
tags:
  - name: faq
    description: FAQ
  - name: announcement
    description: 공지사항
  - name: guide
    description: |-
      - 가이드는 PDF를 다운로드 받는 형태로 제공할 예정
      - [TODO] SuperUX 내 파일 다운로드 기능 확인필요
      - [TODO] PDF형태로 제공할 것인지 UX와 협의 필요
  - name: faq / announcement (와플 게시판)
    description: |-
      - guide / faq / announcementsms 전형적인 게시판형 기능에 속함
      - 게시판 관련 컴포넌트는 와플 게시판을 통해 구현한다는 내용이 있었음 
      - 해당 내용에 대한 진척사항, 히스토리 파악 필요
paths:
  /faq:
    get:
      tags:
        - faq
      summary: FAQ 목록 조회
      description: 고객관리 > FAQ관리 FAQ 목록을 조회한다.
      operationId: findFAQ
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
        - name: keyword
          in: query
          description: keyword
          schema:
            type: string
        - name: faqMainType
          in: query
          description: faqMainType
          schema:
            type: string
        - name: faqSubType
          in: query
          description: faqSubType
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FAQ"

  /faq/faqType:
    get:
      tags:
        - faq
      summary: FAQ 유형 목록 조회
      description: 유형탭 구성을 위한 FAQ유형 목록을 조회한다.
      operationId: findFAQTypeWithSubType
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FAQMainTypeWithSubType"

  /announcement:
    get:
      tags:
        - announcement
      summary: 공지사항목록 조회
      description: PM 공지사항 목록을 조회한다.
      operationId: findAnnouncement
      parameters:
        - name: shopId
          in: header
          description: shopId
          required: true
          schema:
            type: string
        - name: keyword
          in: query
          description: keyword
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Announcement"

components:
  schemas:
    FAQ:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: FAQ Id
          example: 10
        mainType:
          $ref: "#/components/schemas/FAQMainType"
        subType:
          $ref: "#/components/schemas/FAQSubType"
        title:
          type: string
          description: FAQ 제목
          example: 현금영수증을 신청하고 싶어요
        content:
          type: string
          description: FAQ 내용
          example: this is sample content
      xml:
        name: faq

    FAQMainType:
      type: object
      description: FAQ main 유형
      properties:
        id:
          type: string
          description: FAQ main 유형ID
          example: 10
        title:
          type: string
          description: FAQ main 유형 제목
          example: 사업자정보
      xml:
        name: faqMainType

    FAQMainTypeWithSubType:
      type: object
      description: FAQ main 유형 (SubType포함)
      properties:
        id:
          type: string
          description: FAQ main 유형ID
          example: 10
        title:
          type: string
          description: FAQ main 유형 제목
          example: 사업자정보
        subTypes:
          type: array
          items:
            $ref: "#/components/schemas/FAQSubType"
      xml:
        name: faqMainTypeWithSubType

    FAQSubType:
      type: object
      description: FAQ sub 유형
      properties:
        id:
          type: string
          description: FAQ sub 유형ID
          example: 10
        title:
          type: string
          description: FAQ sub 유형 제목
          example: 명의변경
      xml:
        name: faqSubType

    Announcement:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: 공지사항Id
          example: 10
        title:
          type: string
          description: 공지사항 제목
          example: (긴급) 공지
        content:
          type: string
          description: 공지사항 내용
          example: this is sample content
        date:
          type: string
          description: 작성일자
          example: 2023-03-07
        image:
          type: array
          items:
            type: string
          description: 상품 이미지
          example: urltest
      xml:
        name: ammouncement
